//state de productos
export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";

//State para el pedido
export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const CONFIRMAR_ORDENAR_PRODUCTO = "CONFIRMAR_ORDENAR_PRODUCTO";
export const MOSTRAR_REUSMEN = "MOSTRAR_REUSMEN";
export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
